import { getDatabase } from './database.js';

export interface AuthUserRecord { id: string; email: string; name: string; avatarUrl: string; googleId: string; isVerified: boolean; createdAt: string; updatedAt: string; tokenVersion: number; }
export interface OtpRecord { id: string; email: string; code: string; expiresAt: string; used: boolean; }
type Row = Record<string, unknown>;
const user = (row: Row): AuthUserRecord => ({ id: String(row.id), email: String(row.email), name: String(row.name ?? ''), avatarUrl: String(row.avatar_url ?? ''), googleId: String(row.google_id ?? ''), isVerified: Boolean(row.is_verified), tokenVersion: Number(row.token_version), createdAt: new Date(String(row.created_at)).toISOString(), updatedAt: new Date(String(row.updated_at)).toISOString() });

export async function findAuthUserByEmail(email: string): Promise<AuthUserRecord | undefined> { const q = await getDatabase().query('SELECT * FROM users WHERE email = $1', [email.toLowerCase().trim()]); return q.rows[0] && user(q.rows[0]); }
export async function findAuthUserById(id: string): Promise<AuthUserRecord | undefined> { const q = await getDatabase().query('SELECT * FROM users WHERE id = $1', [id]); return q.rows[0] && user(q.rows[0]); }
export async function saveAuthUser(value: AuthUserRecord): Promise<void> {
  await getDatabase().query(`INSERT INTO users (id,email,name,avatar_url,google_id,is_verified,token_version,created_at,updated_at) VALUES ($1,$2,$3,$4,NULLIF($5,''),$6,$7,$8,$9)
    ON CONFLICT (id) DO UPDATE SET email=EXCLUDED.email,name=EXCLUDED.name,avatar_url=EXCLUDED.avatar_url,google_id=EXCLUDED.google_id,is_verified=EXCLUDED.is_verified,token_version=EXCLUDED.token_version,updated_at=EXCLUDED.updated_at`, [value.id, value.email.toLowerCase(), value.name, value.avatarUrl, value.googleId, value.isVerified, value.tokenVersion, value.createdAt, value.updatedAt]);
}
export async function getOrCreateDemoUser(): Promise<AuthUserRecord> { const existing = await findAuthUserByEmail('demo@finance.il'); if (existing) return existing; const now = new Date().toISOString(); const value = { id: '00000000-0000-4000-8000-000000000001', email: 'demo@finance.il', name: 'ישראל ישראלי', avatarUrl: '', googleId: '', isVerified: true, tokenVersion: 0, createdAt: now, updatedAt: now }; await saveAuthUser(value); return value; }
export async function incrementTokenVersion(id: string): Promise<number> { const q = await getDatabase().query('UPDATE users SET token_version=token_version+1,updated_at=now() WHERE id=$1 RETURNING token_version', [id]); return Number(q.rows[0]?.token_version ?? 0); }
export async function getRecentOtps(email: string, windowMs: number): Promise<OtpRecord[]> { const q = await getDatabase().query('SELECT * FROM auth_otp_codes WHERE email=$1 AND created_at > now() - ($2 * interval \'1 millisecond\')', [email, windowMs]); return q.rows.map((r: Row) => ({ id: String(r.id), email: String(r.email), code: String(r.code_hash), expiresAt: new Date(String(r.expires_at)).toISOString(), used: Boolean(r.used_at) })); }
export async function saveOtp(r: OtpRecord): Promise<void> { await getDatabase().query('INSERT INTO auth_otp_codes (id,email,code_hash,expires_at,used_at) VALUES ($1,$2,$3,$4,$5)', [r.id,r.email,r.code,r.expiresAt,r.used ? new Date() : null]); }
export async function getUnusedValidOtps(email: string): Promise<OtpRecord[]> { const q = await getDatabase().query('SELECT * FROM auth_otp_codes WHERE email=$1 AND used_at IS NULL AND expires_at > now() ORDER BY expires_at DESC', [email]); return q.rows.map((r: Row) => ({ id: String(r.id), email: String(r.email), code: String(r.code_hash), expiresAt: new Date(String(r.expires_at)).toISOString(), used: false })); }
export async function markOtpUsed(id: string): Promise<void> { await getDatabase().query('UPDATE auth_otp_codes SET used_at=now() WHERE id=$1 AND used_at IS NULL', [id]); }
